---
- include: redhat.yml
  when: ansible_os_family == 'RedHat'

- include: debian.yml
  when: ansible_os_family == 'Debian'

- name: Install Elasticsearch Curator and required dependencies.
  pip:
    name:
      - elasticsearch-curator
      - argparse

- name: Create elasticsearch-curator config dir
  file:
    path: "{{ elasticsearch_curator_conf_dir }}"
    state: directory

- name: Add Elasticsearch Curator configuration file.
  become: true
  template:
    src: curator.yml.j2
    dest: "{{ elasticsearch_curator_conf_dir }}/curator.yml"

- name: Configure cron jobs for Elasticsearch Curator.
  become: true
  cron:
    name: "{{ item.name }}"
    job: "{{ item.job }}"
    minute: "{{ item.minute | default('*') }}"
    hour: "{{ item.hour | default('1') }}"
    day: "{{ item.day | default('*') }}"
    weekday: "{{ item.weekday | default('*') }}"
    month: "{{ item.month | default('*') }}"
  with_items: "{{ elasticsearch_curator_cron_jobs }}"
